---
- hosts: rabbitmq
  become: yes
  gather_facts: no
  tasks:
    - name: ensure trusted key is added
      apt_key:
        url: 'https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc'
        state: present
#    - name: ensure rabbitmq repositories are added
#      apt_repository:
#        repo: '{{ item }}'
#        state: present
#      with_items:
#        - 'deb https://dl.bintray.com/rabbitmq-erlang/debian focal erlang'
#        - 'deb https://dl.bintray.com/rabbitmq/debian/ focal main'
    - name: ensure package is installed
      apt:
        name: rabbitmq-server
    - name: ensure rabbitmq plugins are installed
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - restart rabbitmq
  handlers:
    - name: restart rabbitmq
      service:
        name: rabbitmq-server
        state: restarted

- hosts: rabbitmq
  become: yes
  gather_facts: no
  tasks:
    - name: ensure rabbitmq user is present
      rabbitmq_user:
        user: '{{ rabbitmq_user }}'
        password: '{{ rabbitmq_password }}'
        tags: administrator
        vhost: /
        configure_priv: .*
        write_priv: .*
        read_priv: .*
        state: present
    - name: ensure guest user is absent
      rabbitmq_user:
        user: guest
        state: absent
